### ISSUE TITLE
Latest release gives compile error, refuses to build

### ISSUE THREAD

**Issue by ssuess** [xaksis/vue-good-table#48]
```
Errors:
  2  http://eslint.org/docs/rules/semi

 @ multi ./build/hot-reload ./src/main.js

 error  in ./~/vue-good-table/src/components/Table.vue

Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/stephen/takeaction_quasar14/node_modules/vue-good-table"
    at /Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/stephen/takeaction_quasar14/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/takeaction_quasar14/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/Users/stephen/takeaction_quasar14/node_modules/babel-loader/lib/index.js:174:20)

 @ ./~/vue-good-table/src/components/Table.vue 8:2-92
 @ ./~/vue-good-table/src/index.js
 @ ./src/main.js
 @ multi ./build/hot-reload ./src/main.js

```
Previous build worked fine...

**Comment by ssuess** [comment]
Sorry I spoke too soon...this is related to a change in dev environment...still investigating...

**Comment by ssuess** [comment]
hm, per [this issue](https://github.com/babel/babel-preset-env/issues/186) I tried to install babel-preset-env which did allow it to build, but now results in a blank page and error: `Uncaught TypeError: Cannot read property 'installed' of undefined`

**Comment by xaksis** [comment]
@ssuess where are you seeing that error? I suspect this is unrelated to vue-good-table.

**Comment by ssuess** [comment]
```
vue.runtime.esm.js?a427:4105 Uncaught TypeError: Cannot read property 'installed' of undefined
    at Function.Vue.use (vue.runtime.esm.js?a427:4105)
    at eval (main.js?1c90:23)
    at Object.<anonymous> (app.js:1611)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at Object.<anonymous> (app.js:1921)
    at __webpack_require__ (app.js:689)
    at app.js:790
    at app.js:793
```
It could be unrelated, but no other component is throwing this error...

**Comment by xaksis** [comment]
how are you including the plugins? can you paste your code so I get more context?

**Comment by ssuess** [comment]
how am I including them?  You mean in main js or the vue files? I am doing both, either in main.js like:

```
import VueGoodTable from 'vue-good-table'
Vue.use(VueGoodTable)
```
Or in the view files like

```
import VueGoodTable from 'vue-good-table'
export default {
  props: {
    list: Array
  },
  components: {
    VueGoodTable
  },

```

**Comment by xaksis** [comment]
looks correct, but if you include in the main.js, you shouldn't need to include it again in view files... unless they're in different projects?

**Comment by ssuess** [comment]
No I just meant I have tried both separately, not both at the same time. And I am blocked on this error, which is strange, because in another project your module works just fine...I am going through the list of module differences between projects to see if I can find what is missing or different...

**Comment by xaksis** [comment]
alright... it's tough for me to investigate this since I cannot reproduce it. let me know what you find out.

**Comment by ssuess** [comment]
UGH I found it. It was related to another import line that I have erroneously pasted over with the import line from vue-good-table. Sorry to have bothered you, and thanks for the responses!

**Comment by xaksis** [comment]
no prob. glad you were able to resolve it.
