### ISSUE TITLE
Unit test: cannot read property '$scopedSlots' of undefined

### ISSUE THREAD

**Issue by teslor** [xaksis/vue-good-table#559]
I have a component where I use vue-good-table. I created tests for it using Mocha, and one of the tests is used to check the contents of the table and this test fails with error `[Vue warn]: Error in callback for immediate watcher "searchOptions": "TypeError: Cannot read property '$scopedSlots' of undefined"
`. If I run this test alone it works ok, but otherwise it fails (wrappers are correctly cleared before each test so it's not the issue).

Probaly it's related to https://github.com/vuejs/vue-test-utils/issues/1130. If you are sure it's not a vue-good-table issue this one can be closed.

Here is a fragment of stacktrace related to vue-good-table:
```
      at C:\Web\Test\dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1783:1
      at arrayEach (dist\webpack:\node_modules\lodash.foreach\index.js:35:1)
      at forEach (dist\webpack:\node_modules\lodash.foreach\index.js:290:1)
      at C:\Web\Test\dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1782:1
      at arrayEach (dist\webpack:\node_modules\lodash.foreach\index.js:35:1)
      at forEach (dist\webpack:\node_modules\lodash.foreach\index.js:290:1)
      at VueComponent.unselectAllInternal (dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1781:1)
      at VueComponent.resetTable (dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1935:1)
      at VueComponent.handleSearch (dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1754:1)
      at VueComponent.handler (dist\webpack:\node_modules\vue-good-table\dist\vue-good-table.es.js:1401:1)
```

### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
vue-good-table 2.16.5, vue 2.6.10, vue-test-utils 1.0.0-beta.29

**Comment by xaksis** [comment]
Hi @teslor, this very much looks to me a vue-test-utils issue (when manipulating data in a watcher) as this is happening even with vuetify datatable. I'm going to close this for now and keep an eye on the vue-test-util bug.
