### ISSUE TITLE
Cannot run app with basic table

### ISSUE THREAD

**Issue by malet-pr** [xaksis/vue-good-table#967]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
I don´t know, it doesn´t say. I just installed it (2023/10/11)

What browser?
Google Chrome on Centos 9

### Expected Behavior
I expected to see the basic table

### Actual Behavior
I get this error in the console and the app will not start
vue-good-table.esm.js:9203 Uncaught TypeError: _this6.$set is not a function
    at vue-good-table.esm.js:9203:18
    at Proxy.forEach (<anonymous>)
    at vue-good-table.esm.js:9202:28
    at Proxy.forEach (<anonymous>)
    at Proxy.unselectAllInternal (vue-good-table.esm.js:9201:12)
    at Proxy.resetTable (vue-good-table.esm.js:9381:12)
    at Proxy.handleSearch (vue-good-table.esm.js:9174:12)
    at Proxy.handler10 (vue-good-table.esm.js:8728:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)

### Steps to Reproduce the Problem
Please detail your steps here

1.  I copied the basic example in https://xaksis.github.io/vue-good-table/guide/#installation
2. Added the component to App.vue
3. I run the app.
4. (I am using composition API)

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by saturnonfire** [comment]
Up! 
The same issue - example from documentation just dont work. The problem is in this method
`
unselectAllInternal: function unselectAllInternal(forceAll) {
      var _this6 = this;
      var rows = this.selectAllByPage && !forceAll ? this.paginated : this.filteredRows;
      rows.forEach(function (headerRow, i) {
        headerRow.children.forEach(function (row, j) {
          _this6.$set(row, 'vgtSelected', false);
        });
      });
      this.emitSelectedRows();
    },`

**Comment by azriel49** [comment]
Same thing  for me
